
package com.sf.module.serviceprovide.service;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-11-12T22:22:45.384+08:00
 * Generated source version: 2.6.2
 * 
 */
 
public class ICustomerService_CustomerServicePort_Server{

    protected ICustomerService_CustomerServicePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ICustomerServiceImpl();
        String address = "http://219.134.187.154:8088/bsp-oip/ws/CustomerService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new ICustomerService_CustomerServicePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
