package com.sf.module.serviceprovide.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-11-12T22:22:45.374+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://service.serviceprovide.module.sf.com/", name = "ICustomerService")
@XmlSeeAlso({ObjectFactory.class})
public interface ICustomerService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "logisticQueryStandard", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.LogisticQueryStandard")
    @WebMethod
    @ResponseWrapper(localName = "logisticQueryStandardResponse", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.LogisticQueryStandardResponse")
    public java.lang.String logisticQueryStandard(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "routeTrackingService", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.RouteTrackingService")
    @WebMethod
    @ResponseWrapper(localName = "routeTrackingServiceResponse", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.RouteTrackingServiceResponse")
    public java.lang.String routeTrackingService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryMailnoDetailService", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.QueryMailnoDetailService")
    @WebMethod
    @ResponseWrapper(localName = "queryMailnoDetailServiceResponse", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.QueryMailnoDetailServiceResponse")
    public java.lang.String queryMailnoDetailService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "orderMailBindingService", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.OrderMailBindingService")
    @WebMethod
    @ResponseWrapper(localName = "orderMailBindingServiceResponse", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.OrderMailBindingServiceResponse")
    public java.lang.String orderMailBindingService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "orderService", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.OrderService")
    @WebMethod
    @ResponseWrapper(localName = "orderServiceResponse", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.OrderServiceResponse")
    public java.lang.String orderService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "cancelOrderService", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.CancelOrderService")
    @WebMethod
    @ResponseWrapper(localName = "cancelOrderServiceResponse", targetNamespace = "http://service.serviceprovide.module.sf.com/", className = "com.sf.module.serviceprovide.service.CancelOrderServiceResponse")
    public java.lang.String cancelOrderService(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
