package com.sf.module.serviceprovide.service;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-11-12T22:22:45.394+08:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "CustomerServiceService", 
                  wsdlLocation = "http://219.134.187.154:8088/bsp-oip/ws/CustomerService?wsdl",
                  targetNamespace = "http://service.serviceprovide.module.sf.com/") 
public class CustomerServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.serviceprovide.module.sf.com/", "CustomerServiceService");
    public final static QName CustomerServicePort = new QName("http://service.serviceprovide.module.sf.com/", "CustomerServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://219.134.187.154:8088/bsp-oip/ws/CustomerService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://219.134.187.154:8088/bsp-oip/ws/CustomerService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
   

    /**
     *
     * @return
     *     returns ICustomerService
     */
    @WebEndpoint(name = "CustomerServicePort")
    public ICustomerService getCustomerServicePort() {
        return super.getPort(CustomerServicePort, ICustomerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ICustomerService
     */
    @WebEndpoint(name = "CustomerServicePort")
    public ICustomerService getCustomerServicePort(WebServiceFeature... features) {
        return super.getPort(CustomerServicePort, ICustomerService.class, features);
    }

}
