
package com.sf.module.serviceprovide.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-11-12T22:22:45.214+08:00
 * Generated source version: 2.6.2
 * 
 */
public final class ICustomerService_CustomerServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.serviceprovide.module.sf.com/", "CustomerServiceService");

    private ICustomerService_CustomerServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerServiceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CustomerServiceService ss = new CustomerServiceService(wsdlURL, SERVICE_NAME);
        ICustomerService port = ss.getCustomerServicePort();  
        
        {
        System.out.println("Invoking logisticQueryStandard...");
        java.lang.String _logisticQueryStandard_arg0 = "";
        java.lang.String _logisticQueryStandard__return = port.logisticQueryStandard(_logisticQueryStandard_arg0);
        System.out.println("logisticQueryStandard.result=" + _logisticQueryStandard__return);


        }
        {
        System.out.println("Invoking routeTrackingService...");
        java.lang.String _routeTrackingService_arg0 = "";
        java.lang.String _routeTrackingService__return = port.routeTrackingService(_routeTrackingService_arg0);
        System.out.println("routeTrackingService.result=" + _routeTrackingService__return);


        }
        {
        System.out.println("Invoking queryMailnoDetailService...");
        java.lang.String _queryMailnoDetailService_arg0 = "";
        java.lang.String _queryMailnoDetailService__return = port.queryMailnoDetailService(_queryMailnoDetailService_arg0);
        System.out.println("queryMailnoDetailService.result=" + _queryMailnoDetailService__return);


        }
        {
        System.out.println("Invoking orderMailBindingService...");
        java.lang.String _orderMailBindingService_arg0 = "";
        java.lang.String _orderMailBindingService__return = port.orderMailBindingService(_orderMailBindingService_arg0);
        System.out.println("orderMailBindingService.result=" + _orderMailBindingService__return);


        }
        {
        System.out.println("Invoking orderService...");
        java.lang.String _orderService_arg0 = "";
        java.lang.String _orderService__return = port.orderService(_orderService_arg0);
        System.out.println("orderService.result=" + _orderService__return);


        }
        {
        System.out.println("Invoking cancelOrderService...");
        java.lang.String _cancelOrderService_arg0 = "";
        java.lang.String _cancelOrderService__return = port.cancelOrderService(_cancelOrderService_arg0);
        System.out.println("cancelOrderService.result=" + _cancelOrderService__return);


        }

        System.exit(0);
    }

}
