<tporder>
	<orderid>${orderId}</orderid>
	<tradeno>${tradeNo}</tradeno>
	<logistic_provider>${logisticProviderID}</logistic_provider>
	<apply_type>${applyType}</applyType>
	<ewaybill_size>${ewaybillSize}</ewaybill_size>
	<j_custid>${custId}</j_custid>
	<j_custtag>${custTag}</j_custtag>
	<j_company>${companyName}</j_company>
	<j_contact>${senderUserName}</j_contact>
	<j_postcode>${senderPostCode}</j_postcode>
	<j_tel>${senderPhone}</j_tel>
	<j_mobile>${senderMobile}</j_mobile>
	<j_province>${senderPostProv}</j_province>
	<j_city>${senderPostCity}</j_city>
	<j_county>${senderPostArea}</j_county>
	<j_address>${senderAddress}</j_address>
	<d_company></d_company>
	<d_contact>${receiverUserName}</d_contact>
	<d_postcode>${receiverPostCode}</d_postcode>
	<d_tel>${receiverPhone}</d_tel>
	<d_mobile>${receiverMobile}</d_mobile>
	<d_province>${receiverPostProv}</d_province>
	<d_city>${receiverPostCity}</d_cityid>
	<d_county>${receiverPostArea}</d_county>
	<d_address>${receiverAddress}</d_address>
	<cargo>${cargo}</cargo>
	<parcel_quantity>${parcelQuantity}</parcel_quantity>
	<cargo_total_weight>${cargoTotalWeight}</cargo_total_weight>
	<cargo_net_weight>${cargoNetWeight}</cargo_net_weight >
	<express_type>${expressType}</express_type>
	<is_cod>${isCod}</is_cod>
	<cod_amount>${codAmount}</cod_amount>
	<pay_method>${payMethod}</pay_method>
	<pay_custid>${payCustid}</pay_custid>
	<is_insurance>${isInsurance}</is_insurance>
	<insurance_amount>${insuranceAmount}</insurance_amount>
	<remark>${remark}</remark>
	<sendstarttime>${sendStartTime}</sendstarttime>
	<sendendtime>${sendEndTime}</sendendtime>
	<checkword>${checkWord}</checkword>
	<j_cityid>${jCityId}</j_cityid>
	<d_cityid>${dCityId}</d_cityid>
	<cargo_length></cargo_length>
	<cargo_width></cargo_width>
	<cargo_height></cargo_height>
	<filter1></filter1>
	<filter2></filter2>
	<filter3></filter3>
	<filter4></filter4>
	<filter5></filter5>
	<filter6></filter6>
	<filter7></filter7>
	<filter8></filter8>
	<filter9></filter9>
	<filter10></filter10>
	<filter11>/filter11>
	<filter12></filter12>
	<filter13></filter13>
	<filter14></filter14>
	<filter15></filter15>
	<filter16></filter16>
	<filter17></filter17>
	<filter18></filter18>
	<filter19></filter19>
	<filter20></filter20>
</tporder>
